const FRONT_SECRETKEY = 'front_666666'
const BACKEND_SECRETKEY = 'backend_666666'
const TOKEN_SECRETKEY = 'token_666666'

module.exports = {
    FRONT_SECRETKEY,
    BACKEND_SECRETKEY,
    TOKEN_SECRETKEY
}